### ISSUE TITLE
Progress bar for Ruffle

### ISSUE THREAD

**Issue by vlad185** [ruffle-rs/ruffle#2302]
Hi,

When loading a flash game, a blank screen is displayed and if the file is large, it does not look very attractive.
The user may think that the game is not working and will not wait for the download.
How can you implement a progress bar when loading a game through ruffle?

Thanks

**Comment by Poopooracoocoo** [comment]
#875

**Comment by jrob007** [comment]
While this doesn't make up for an actual loading indicator of ruffle.js and its WASM file, I figured I'd share a purely CSS solution I did for a company site which now utilizes Ruffle for loading their SWFs by using an extra HTML element and some positioning. At the very minimum this shows _something_ while Ruffle is being loaded for a new visitor so they aren't stuck looking at just a blank screen. Here it's just some text and a tiny animated GIF. Once the movie loads, the player element visually overlaps the loading element. In my case my SWF dimensions have a 16:9 aspect ratio. Your usage may vary.

Javascript
```
window.RufflePlayer = window.RufflePlayer || {};
window.addEventListener("load", (event) => {
	const ruffle = window.RufflePlayer.newest();
	const player = ruffle.createPlayer();
	const container = document.getElementById("my-player");
	const wrapper = document.getElementById("my-player-wrapper");
	const wrapperInfo = wrapper.getBoundingClientRect();
	player.style.width = '100%';
	player.style.height = Math.ceil((wrapperInfo.width * 9) / 16) + 'px';
	container.appendChild(player);
	container.style.width = player.style.width;
	container.style.height = player.style.height;
	player.load("movie.swf");
});
```

HTML
```
<div id="my-player-wrapper">
	<div id="my-player-loading">Loading Ruffle, just a moment...<img src="loading.gif" alt=""></div>
	<div id="my-player"></div>
</div>
```

CSS
```
#my-player-wrapper {
	position: relative;
}

#my-player-loading {
	position: absolute;
	top: 50%;
	left: 50%;
	width: 300px;
	margin-left: -150px;
	text-align: center;
	z-index: 1;
}

#my-player-loading img {
	display: block;
	margin: 0 auto;
}

#my-player {
	position: relative;
	z-index: 2;
}
```

**Comment by vlad185** [comment]
Thanks buddy, it's better than a blank screen.

**Comment by paxperscientiam** [comment]
As an alternative based off of @jrob007's work, I've gone with this:

 CSS animation is from some website; don't remember which.
```CSS

.ruffle-container-wrapper {
    position: relative;
}

.ruffle-container {
    position: relative;
    z-index: 2;
}

.ruffle-loader {
  font-size: 10px;
  margin: 50px auto;
  text-indent: -9999em;
  width: 11em;
  height: 11em;
  border-radius: 50%;
  background: #ffffff;
  background: -moz-linear-gradient(left, #ffffff 10%, rgba(255, 255, 255, 0) 42%);
  background: -webkit-linear-gradient(left, #ffffff 10%, rgba(255, 255, 255, 0) 42%);
  background: -o-linear-gradient(left, #ffffff 10%, rgba(255, 255, 255, 0) 42%);
  background: -ms-linear-gradient(left, #ffffff 10%, rgba(255, 255, 255, 0) 42%);
  background: linear-gradient(to right, #ffffff 10%, rgba(255, 255, 255, 0) 42%);
  position: relative;
  -webkit-animation: load3 1.4s infinite linear;
  animation: load3 1.4s infinite linear;
  -webkit-transform: translateZ(0);
  -ms-transform: translateZ(0);
  transform: translateZ(0);
}
.ruffle-loader:before {
  width: 50%;
  height: 50%;
  background: black;
  border-radius: 100% 0 0 0;
  position: absolute;
  top: 0;
  left: 0;
  content: '';
}
.ruffle-loader:after {
  background: #f5f5f5;
  width: 75%;
  height: 75%;
  border-radius: 50%;
  content: '';
  margin: auto;
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
}
@-webkit-keyframes load3 {
  0% {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  100% {
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}
@keyframes load3 {
  0% {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  100% {
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}
```

```JS
function styleRufflePlayButton() {
    jQuery("ruffle-player").each(function(i, el) {
        const playbutton = el.shadow.getElementById("play_button");
        if (null != playbutton) {
		        playbutton.style.background = "black"; 
        }
    });
};

function doRuffle(swf_path, container_id, wrapper_id) {
    window.RufflePlayer = window.RufflePlayer || {};
    const ruffle = window.RufflePlayer.newest();
    const player = ruffle.createPlayer();
    player.style.width = "100%";
    const container = document.getElementById(container_id);
    const wrapper = document.getElementById(wrapper_id);
    const wrapperInfo = wrapper.getBoundingClientRect();
    container.appendChild(player);
    player.load(swf_path)
        .then(() => {
	        styleRufflePlayButton()
            jQuery(".ruffle-loader", container).remove();
            console.log('Ruffle loaded');
        })
        .catch((e) => {
            console.error(`Ruffle failed to load the file: ${e}`);
        });
}
```


Use example:
```HTML
<div id="container-wrapper" class="ruffle-container-wrapper">
	<div id="container" class="ruffle-container">
	  <div class="ruffle-loader"></div>
  	</div>
</div>

<script>
 window.addEventListener("load", (event) => {
    doRuffle("/wp-content/uploads/custom_resources_sdaff32dasa/clock_prototype.swf", "container", "container-wrapper");
});
</script>   
```

in action: https://www.icloud.com/iclouddrive/0WBVb5R1pX4GboJKAYTRU3bwQ#Screen_Recording_2021-06-02_at_4.51.00_PM

Painfully slow in my opinion.
