### ISSUE TITLE
Provide permalink to latest nightly Ruffle build assets (for automated deployment)

### ISSUE THREAD

**Issue by digitalcircuit** [ruffle-rs/ruffle#3053]
**Describe the bug**
Ruffle does not seem to provide a way to download the latest release without navigating the GitHub releases page, or HTML scraping the https://ruffle.rs/ website.

**Expected behavior**
Ruffle could have a statically named tag (e.g. `latest_nightly`) that is [updated by `release_nightly.yaml`]( ruffle/.github/workflows/release_nightly.yml  ), similar to the existing Arch package support.

This would simplify automated nightly/weekly deployments of the prebuilt version of Ruffle.

**Additional information**
The logical flow might be like this:
1.  Set up a secondary job called `create-latest-nightly-release`
2.  Run only if `create-nightly-release` runs
3.  Recreate a new release with tag named `latest_nightly`, using [GongT/actions-recreate-release@v1](https://github.com/GongT/actions-recreate-release )
```yml
      - name: Recreate release permalink
        if: env.GHA_REPO_ALIVE == 'true'
        id: create_release
        uses: GongT/actions-recreate-release@v1
        # Until https://github.com/actions/create-release/issues/29 is addressed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest-nightly
          release_name: Nightly ${{ steps.current_time_dashes.outputs.formattedTime }}
          prerelease: true
```
4.  After build, upload to the latest release as well

Alternatively, the GitHub CI workflow could be given permission to update a static link on the ruffle.rs hosting infrastructure.

Or, if the GitHub Actions workflow uploads build artifacts (not just release artifacts), [`nightly.link`](https://nightly.link) could be used.  See [Quassel IRC's usage here to provide a stable `latest` link](https://github.com/quassel/quassel/commit/f13f99af5bfd21d8a052f26f4b08a22da5e69333 ).

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
It applies to all versions of Ruffle.

**What platform are you using?**
 - Ubuntu Linux 18.04 LTS, Firefox 85 (though this applies to all platforms, it's CI infrastructure)
